#%RAML 1.0
title: HackLine time tracking API
baseUri: http://hackline.io/api
version: 1.0

types:
  running: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "title": {
          "type": "string",
          "required": true,
          "description": "The title of the running interval."
        },
        "start": {
          "type": "integer",
          "required": true,
          "description": "The start time of the currently running interval in millis since epoch."
        },
        "end": {
          "type": "integer",
          "required": false,
          "description": "If the interval ends, the end time in millis since epoch."
        },
        "fallback": {
          "type": "string",
          "required": false,
          "description": "If the currently running interval will end, this is the next interval title."
        }
      }
    }
  change-running: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "id": "http://jsonschema.net",
      "required": true,
      "properties": {
        "title": {
          "type": "string",
          "required": true,
          "description": "The title of the interval."
        },
        "start": {
          "type": "integer",
          "required": false,
          "description": "The start time, in millis since epoch, must be before the current time, defualt is current time."
        }
      }
    }

/running:
  get:
    description: |
      Get the currently running interval.
    headers:
        api-key:
          description: "The Api-Key"
          required: true
          type: string
    responses:
      200:
        body:
          application/json:
            type: running
            example: |
              {
                "title": "Productive",
                "start": 1688414824894,
                "end": 1688414824894,
                "fallback": "Non-productive"
              }
  put:
    description: |
      Change the currently running interval.
    headers:
        api-key:
          description: "The Api-Key"
          required: true
          type: string
    body:
        application/json:
          type: change-running
    responses:
      200:
        description: |
          The updated current running interval.
        body:
          application/json:
            type: running
            example: |
              {
                "title": "Productive",
                "start": 1688414824894
              }

/timeline:
  get:
  post:
  put:

/settings:
  get:
  post:
  patch:
  put:
  delete:

